[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"

[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'self' 'nonce-{nonce}'; style-src 'self' 'nonce-{nonce}'; img-src 'self' https://ioninteractive.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://api.example.com https://cdnjs.cloudflare.com; frame-src 'none'; worker-src 'self';"
