[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
    reportOnly = false
    excludedPath = ["/api/*"]  # escludi API se serve


## Rewrite image URLs marked with imgcdn=true to use Netlify Image CDN
[[redirects]]
  from = "/*"
  query = {imgcdn = "true"}
  to = "/.netlify/images?url=/:splat&fm=webp"
  status = 200
  force = true
